### ISSUE TITLE
NOPE TRY AGAIN

### ISSUE THREAD

**Issue by carlosdarienvizcaino** [chausen/TigerZoneServer#4]
The message "NOPE TRY AGAIN" lacks content in order for the client to know what is wrong. 
![image](https://cloud.githubusercontent.com/assets/9055341/20821800/98971c3c-b813-11e6-903b-39dd00b13199.png)

This message appears in several classes and numerous times. 
Thanks.

**Comment by chausen** [comment]
It doesn't look like Dave has this listed in v1.4 of the protocol, **but it is part of the login protocol** and is displayed when the login credentials provided are incorrect. Since the credentials are provided to you prior to the tournament, it isn't a message your AI should ever receive anyways. I will let Dave know though that is missing from the published protocol.
